export const ASSESSMENT_STORE_REQUEST = 'ASSESSMENT_STORE_REQUEST';
export const ASSESSMENT_STORE_SUCCESS = 'ASSESSMENT_STORE_SUCCESS';
export const ASSESSMENT_STORE_FAILED = 'ASSESSMENT_STORE_FAILED';
export const ASSESSMENT_STORE_RESET = 'ASSESSMENT_STORE_RESET';

export const ASSESSMENT_EDIT_REQUEST = 'ASSESSMENT_EDIT_REQUEST';
export const ASSESSMENT_EDIT_SUCCESS = 'ASSESSMENT_EDIT_SUCCESS';
export const ASSESSMENT_EDIT_FAILED = 'ASSESSMENT_EDIT_FAILED';
export const ASSESSMENT_EDIT_RESET = 'ASSESSMENT_EDIT_RESET';

export const ASSESSMENT_SHOWLIST_REQUEST = 'ASSESSMENT_SHOWLIST_REQUEST';
export const ASSESSMENT_SHOWLIST_SUCCESS = 'ASSESSMENT_SHOWLIST_SUCCESS';
export const ASSESSMENT_SHOWLIST_FAILED = 'ASSESSMENT_SHOWLIST_FAILED';

export const ASSESSMENT_DELETE_REQUEST = 'ASSESSMENT_DELETE_REQUEST';
export const ASSESSMENT_DELETE_SUCCESS = 'ASSESSMENT_DELETE_SUCCESS';
export const ASSESSMENT_DELETE_FAILED = 'ASSESSMENT_DELETE_FAILED';
export const ASSESSMENT_DELETE_RESET = 'ASSESSMENT_DELETE_RESET';

export const ASSESSMENT_ACTIVATION_REQUEST = 'ASSESSMENT_ACTIVATION_REQUEST';
export const ASSESSMENT_ACTIVATION_SUCCESS = 'ASSESSMENT_ACTIVATION_SUCCESS';
export const ASSESSMENT_ACTIVATION_FAILED = 'ASSESSMENT_ACTIVATION_FAILED';
export const ASSESSMENT_ACTIVATION_RESET = 'ASSESSMENT_ACTIVATION_RESET';

export const ASSESSMENT_SHOWONE_REQUEST = 'ASSESSMENT_SHOWONE_REQUEST';
export const ASSESSMENT_SHOWONE_SUCCESS = 'ASSESSMENT_SHOWONE_SUCCESS';
export const ASSESSMENT_SHOWONE_FAILED = 'ASSESSMENT_SHOWONE_FAILED';

export const ASSESSMENT_ORDER_REQUEST = 'ASSESSMENT_ORDER_REQUEST';
export const ASSESSMENT_ORDER_SUCCESS = 'ASSESSMENT_ORDER_SUCCESS';
export const ASSESSMENT_ORDER_FAILED = 'ASSESSMENT_ORDER_FAILED';
export const ASSESSMENT_ORDER_RESET = 'ASSESSMENT_ORDER_RESET';

export const ASSESSMENT_USERS_REQUEST = 'ASSESSMENT_USERS_REQUEST';
export const ASSESSMENT_USERS_SUCCESS = 'ASSESSMENT_USERS_SUCCESS';
export const ASSESSMENT_USERS_FAILED = 'ASSESSMENT_USERS_FAILED';
export const ASSESSMENT_USERS_RESET = 'ASSESSMENT_USERS_RESET';

export const ASSESSMENT_PACKAGES_REQUEST = 'ASSESSMENT_PACKAGES_REQUEST';
export const ASSESSMENT_PACKAGES_SUCCESS = 'ASSESSMENT_PACKAGES_SUCCESS';
export const ASSESSMENT_PACKAGES_FAILED = 'ASSESSMENT_PACKAGES_FAILED';

export const ASSESSMENT_SHOWONEPACKAGE_REQUEST = 'ASSESSMENT_SHOWONEPACKAGE_REQUEST';
export const ASSESSMENT_SHOWONEPACKAGE_SUCCESS = 'ASSESSMENT_SHOWONEPACKAGE_SUCCESS';
export const ASSESSMENT_SHOWONEPACKAGE_FAILED = 'ASSESSMENT_SHOWONEPACKAGE_FAILED';

export const ASSESSMENT_SYSTEMSLIST_REQUEST = 'ASSESSMENT_SYSTEMSLIST_REQUEST';
export const ASSESSMENT_SYSTEMSLIST_SUCCESS = 'ASSESSMENT_SYSTEMSLIST_SUCCESS';
export const ASSESSMENT_SYSTEMSLIST_FAILED = 'ASSESSMENT_SYSTEMSLIST_FAILED';
export const ASSESSMENT_SYSTEMSLIST_RESET = 'ASSESSMENT_SYSTEMSLIST_RESET';

export const ASSESSMENT_USERSBYQUESTIONNAIRE_REQUEST = 'ASSESSMENT_USERSBYQUESTIONNAIRE_REQUEST';
export const ASSESSMENT_USERSBYQUESTIONNAIRE_SUCCESS = 'ASSESSMENT_USERSBYQUESTIONNAIRE_SUCCESS';
export const ASSESSMENT_USERSBYQUESTIONNAIRE_FAILED = 'ASSESSMENT_USERSBYQUESTIONNAIRE_FAILED';
