export const PAYMENT_DISCOUNTCODE_REQUEST = 'PAYMENT_DISCOUNTCODE_REQUEST';
export const PAYMENT_DISCOUNTCODE_SUCCESS = 'PAYMENT_DISCOUNTCODE_SUCCESS';
export const PAYMENT_DISCOUNTCODE_FAILED = 'PAYMENT_DISCOUNTCODE_FAILED';
