export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

export const AUTH_ENTERPHONE_REQUEST = 'AUTH_ENTERPHONE_REQUEST';
export const AUTH_ENTERPHONE_SUCCESS = 'AUTH_ENTERPHONE_SUCCESS';
export const AUTH_ENTERPHONE_FAILED = 'AUTH_ENTERPHONE_FAILED';

export const AUTH_ENTERCODE_REQUEST = 'AUTH_ENTERCODE_REQUEST';
export const AUTH_ENTERCODE_SUCCESS = 'AUTH_ENTERCODE_SUCCESS';
export const AUTH_ENTERCODE_FAILED = 'AUTH_ENTERCODE_FAILED';
