export const PROFILE_EDIT_REQUEST = 'PROFILE_EDIT_REQUEST';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';
export const PROFILE_EDIT_FAILED = 'PROFILE_EDIT_FAILED';

export const PROFILE_DASHBOARD_REQUEST = 'PROFILE_DASHBOARD_REQUEST';
export const PROFILE_DASHBOARD_SUCCESS = 'PROFILE_DASHBOARD_SUCCESS';
export const PROFILE_DASHBOARD_FAILED = 'PROFILE_DASHBOARD_FAILED';
