export const USER_SHOWLIST_REQUEST = 'USER_SHOWLIST_REQUEST';
export const USER_SHOWLIST_SUCCESS = 'USER_SHOWLIST_SUCCESS';
export const USER_SHOWLIST_FAILED = 'USER_SHOWLIST_FAILED';

export const ALLUSERS_SHOWLIST_REQUEST = 'ALLUSERS_SHOWLIST_REQUEST';
export const ALLUSERS_SHOWLIST_SUCCESS = 'ALLUSERS_SHOWLIST_SUCCESS';
export const ALLUSERS_SHOWLIST_FAILED = 'ALLUSERS_SHOWLIST_FAILED';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILED = 'USER_DELETE_FAILED';

export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAILED = 'USER_EDIT_FAILED';

export const USER_ADDGROUP_REQUEST = 'USER_ADDGROUP_REQUEST';
export const USER_ADDGROUP_SUCCESS = 'USER_ADDGROUP_SUCCESS';
export const USER_ADDGROUP_FAILED = 'USER_ADDGROUP_FAILED';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const USER_SHOWONE_REQUEST = 'USER_SHOWONE_REQUEST';
export const USER_SHOWONE_SUCCESS = 'USER_SHOWONE_SUCCESS';
export const USER_SHOWONE_FAILED = 'USER_SHOWONE_FAILED';

export const USER_CANCELASSIGN_REQUEST = 'USER_CANCELASSIGN_REQUEST';
export const USER_CANCELASSIGN_SUCCESS = 'USER_CANCELASSIGN_SUCCESS';
export const USER_CANCELASSIGN_FAILED = 'USER_CANCELASSIGN_FAILED';

export const USER_ASSIGN_REQUEST = 'USER_ASSIGN_REQUEST';
export const USER_ASSIGN_SUCCESS = 'USER_ASSIGN_SUCCESS';
export const USER_ASSIGN_FAILED = 'USER_ASSIGN_FAILED';
