export const QUESTIONNAIRE_SHOWLIST_REQUEST = 'QUESTIONNAIRE_SHOWLIST_REQUEST';
export const QUESTIONNAIRE_SHOWLIST_SUCCESS = 'QUESTIONNAIRE_SHOWLIST_SUCCESS';
export const QUESTIONNAIRE_SHOWLIST_FAILED = 'QUESTIONNAIRE_SHOWLIST_FAILED';

export const QUESTIONNAIRE_SHOWONE_REQUEST = 'QUESTIONNAIRE_SHOWONE_REQUEST';
export const QUESTIONNAIRE_SHOWONE_SUCCESS = 'QUESTIONNAIRE_SHOWONE_SUCCESS';
export const QUESTIONNAIRE_SHOWONE_FAILED = 'QUESTIONNAIRE_SHOWONE_FAILED';
