export const GROUP_SHOWLIST_REQUEST = 'GROUP_SHOWLIST_REQUEST';
export const GROUP_SHOWLIST_SUCCESS = 'GROUP_SHOWLIST_SUCCESS';
export const GROUP_SHOWLIST_FAILED = 'GROUP_SHOWLIST_FAILED';

export const GROUP_DELETE_REQUEST = 'GROUP_DELETE_REQUEST';
export const GROUP_DELETE_SUCCESS = 'GROUP_DELETE_SUCCESS';
export const GROUP_DELETE_FAILED = 'GROUP_DELETE_FAILED';

export const GROUP_EDIT_REQUEST = 'GROUP_EDIT_REQUEST';
export const GROUP_EDIT_SUCCESS = 'GROUP_EDIT_SUCCESS';
export const GROUP_EDIT_FAILED = 'GROUP_EDIT_FAILED';

export const GROUP_CREATE_REQUEST = 'GROUP_CREATE_REQUEST';
export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS';
export const GROUP_CREATE_FAILED = 'GROUP_CREATE_FAILED';

export const GROUP_SHOWONE_REQUEST = 'GROUP_SHOWONE_REQUEST';
export const GROUP_SHOWONE_SUCCESS = 'GROUP_SHOWONE_SUCCESS';
export const GROUP_SHOWONE_FAILED = 'GROUP_SHOWONE_FAILED';
